# Generated by Django 6.0.3 on 2026-03-16 22:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioEstoque',
            fields=[
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='inventario', serialize=False, to='produtos.produto')),
                ('quantidade_sistema', models.IntegerField(default=0)),
                ('quantidade_fisica', models.IntegerField(default=0)),
                ('diferenca', models.IntegerField(default=0)),
                ('data_ultima_contagem', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('OK', 'Ok'), ('DIV', 'Divergência')], max_length=20)),
            ],
            options={
                'verbose_name': 'Inventário de Estoque',
                'verbose_name_plural': 'Inventários de Estoque',
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('EN', 'Entrada'), ('SA', 'Saída'), ('AD', 'Ajuste')], max_length=2)),
                ('motivo', models.CharField(choices=[('CO', 'Compra'), ('DEV', 'Devolução'), ('VD', 'Venda'), ('AJ', 'Ajuste'), ('QM', 'Quebra/Máquina'), ('OU', 'Outro')], max_length=3)),
                ('quantidade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('saldo_anterior', models.IntegerField()),
                ('saldo_atual', models.IntegerField()),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True)),
                ('responsavel', models.CharField(blank=True, max_length=100)),
                ('observacoes', models.TextField(blank=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-data_movimentacao'],
            },
        ),
    ]
