# Generated by Django 6.0.3 on 2026-03-16 23:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria de Insumo',
                'verbose_name_plural': 'Categorias de Insumo',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('quantidade_disponivel', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantidade_minima', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantidade_maxima', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0)])),
                ('unidade', models.CharField(choices=[('UN', 'Unidade'), ('CX', 'Caixa'), ('KG', 'Quilograma'), ('MT', 'Metro'), ('ML', 'Mililitro'), ('LT', 'Litro'), ('PC', 'Peça'), ('DZ', 'Dúzia'), ('RM', 'Resma')], default='UN', max_length=2)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('custo_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('localizacao', models.CharField(help_text='Ex: Prateleira A-01', max_length=100)),
                ('status', models.CharField(choices=[('AT', 'Ativo'), ('IN', 'Inativo'), ('DE', 'Descontinuado')], default='AT', max_length=2)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insumos', to='almoxerifado.categoriainsumo')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ['categoria', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoAlmoxarifado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimento', models.CharField(choices=[('EN', 'Entrada'), ('SA', 'Saída'), ('AJ', 'Ajuste'), ('DE', 'Devolução')], max_length=2)),
                ('quantidade', models.IntegerField()),
                ('saldo_anterior', models.IntegerField()),
                ('saldo_atual', models.IntegerField()),
                ('data_movimento', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('documento_ref', models.CharField(blank=True, max_length=50)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historicos', to='almoxerifado.insumo')),
            ],
            options={
                'verbose_name': 'Histórico do Almoxarifado',
                'verbose_name_plural': 'Históricos do Almoxarifado',
                'ordering': ['-data_movimento'],
            },
        ),
        migrations.CreateModel(
            name='EntradaMaterial',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('fornecedor', models.CharField(blank=True, max_length=255)),
                ('numero_nf', models.CharField(blank=True, max_length=20)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('custo_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('observacoes', models.TextField(blank=True)),
                ('usuario_responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='almoxerifado.insumo')),
            ],
            options={
                'verbose_name': 'Entrada de Material',
                'verbose_name_plural': 'Entradas de Material',
                'ordering': ['-data_entrada'],
            },
        ),
        migrations.CreateModel(
            name='RequisicaoMaterial',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('departamento', models.CharField(max_length=100)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PE', 'Pendente'), ('AP', 'Aprovada'), ('RE', 'Recusada'), ('AT', 'Atendida'), ('CA', 'Cancelada')], default='PE', max_length=2)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('motivo_recusa', models.TextField(blank=True)),
                ('usuario_aprovador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_aprovadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes_material', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Requisição de Material',
                'verbose_name_plural': 'Requisições de Material',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='ItemRequisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_solicitada', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('quantidade_atendida', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almoxerifado.insumo')),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='almoxerifado.requisicaomaterial')),
            ],
            options={
                'verbose_name': 'Item de Requisição',
                'verbose_name_plural': 'Itens de Requisição',
            },
        ),
    ]
